FROM maven:3-jdk-8-alpine

RUN apk add --no-cache git

ARG USER_SRC_DIR="/usr/src"

WORKDIR $USER_SRC_DIR

RUN git clone --depth=1 --recursive https://github.com/tananaev/traccar.git

WORKDIR $USER_SRC_DIR/traccar

RUN mvn package
